### ISSUE TITLE
Counting entry replicas should only  from leader's current term.

### ISSUE THREAD

**Issue by linsinn** [async-raft/async-raft#108]
According to the Raft spec:
> To eliminate problems like the one in Figure 8, Raft never commits log entries from previous terms by counting replicas. Only log entries from the leader’s current term are committed by counting replicas; 

While in the code ```calculate_new_commit_index```, this requirement does not seem to be met.

**Comment by thedodd** [comment]
After reviewing the code there, I do believe you are correct. We are passing along the `term` of the entry which has been replicated, but we are not taking it into account within `calculate_new_commit_index`. This appears to be a very simple update:
- pass the `match_term` (the term of the entry which is being considered) as well as the leader's current term.
- if the terms do not match, then just immediately return the value of the current commit index.

@linsinn good eye! And thank you for digging deep into the code like that. Would you be interested in making this change?

**Comment by linsinn** [comment]
Sure, I would like to try.

**Comment by thedodd** [comment]
Related to #109
