### ISSUE TITLE
Question about multi-threaded log apply

### ISSUE THREAD

**Issue by drmingdrmer** [async-raft/async-raft#118]
Isn't there a concurrency issue?
Old logs may be applied after new logs since two bunch of logs are applied in two threads.
https://github.com/async-raft/async-raft/blob/master/async-raft/src/core/append_entries.rs#L258-L264

**Comment by thedodd** [comment]
The `replicate_to_sm_handle` is the mechanism used to ensure that only a single task can replicate data to the state machine, and that is owned by a single task, not shared between multiple threads/tasks. That is not for logs though, that is for state machine. 

For logs, everything is pipelined. A single task owns that routine. There is no parallelism there, only batching.

**Comment by drmingdrmer** [comment]
Thank you @thedodd !
What about adding a piece of comment explaining this? #120
