### ISSUE TITLE
Optimization: Cache replicated entries for faster lookup for applying to state machine.

### ISSUE THREAD

**Issue by thedodd** [async-raft/async-raft#12]
### todo
- [x] Update the append entries algorithm for followers so that recent entries are buffered up to a specific threshold so that the process of applying logs to the state machine will not need to fetch those logs from storage a majority of the time.
- [x] Update the append entries handler so that the process of applying logs to the state machine is no longer directly involved. Right now, applying logs to the state machine is conditionally called when it becomes safe to do so. This needs to be moved to be its own async task.

**Comment by MarinPostma** [comment]
I am currently working on this

**Comment by thedodd** [comment]
@MarinPostma awesome! Keep me posted. I am definitely of the opinion that we should use an async task to handle this responsibility. It can be owned by the RaftCore instance variants as needed. Happy to chat about implementation and design any time!

**Comment by thedodd** [comment]
I'm now hacking on this as I am blocked until its done, so it should be done quite soon `:)`.

**Comment by thedodd** [comment]
Done. About to push/open PR. Hopefully will have a release out very soon. No API changes, so this will be a bug fix release.
