### ISSUE TITLE
Add notes to guide about leader forwarding & version compat.

### ISSUE THREAD

**Issue by thedodd** [async-raft/async-raft#31]

**Comment by thedodd** [comment]
Hey @raultang. 

> the network abstraction seems to be server side handle client request?

That is correct. The expectation is that the app you are building will have some sort of network interface (could be REST, gRPC, websockets, whatever), and basically you just need to have that network interface listen for client requests. When a client request is received, you will need to pass it over to the Raft actor using the `ClientPayload` message type, [described here in the docs](https://docs.rs/actix-raft/0.4.2/actix_raft/messages/struct.ClientPayload.html), and [here in the guide](https://railgun-rs.github.io/actix-raft/raft.html#api).

Something to be aware of is that not every client request will need to flow through Raft. That is application specific. For example, a request to read data from your application does not need to go through Raft, there is no need for it to do so. Only data mutating requests need to go through Raft.

As far as peer to peer communication within the cluster (I think that is what you are asking about in the latter part of your question), that is covered in the [network chapter of the guide](https://railgun-rs.github.io/actix-raft/network.html#trait-raftnetwork). In brief, whatever actor you use to implement the `RaftNetwork` trait, it will need to be able to send RPCs to other peer nodes using the `msg.target` (as you mentioned above).

I know that is a lot to unpack, and I do want to create a simple example (other than in the test code). I hope to have some time to do that soon.

**Comment by raultang** [comment]
@thedodd I wrote one simple example base on your test code, integrated with grpc for network part.

**Comment by thedodd** [comment]
@raultang awesome! I'll checkout that example.

As far as single node, it is already supported. I've been using it quite a lot in the system I've been developing which uses this crate. Take a look: https://railgun-rs.github.io/actix-raft/cluster-formation.html#initwithconfig

The guide goes into more details on this, but once your cluster is configured with more than 1 node, you can't go back down to only one node. It would be a Raft safety violation and such a config change would not be able to be committed by the cluster. As long as you still are able to have a quorum, you can dynamically adjust the cluster size up and down as much as you would like; but once you have more than 1 cluster members, you can't go back down to only 1.

**Comment by raultang** [comment]
@thedodd Thanks, I will try this out.

**Comment by thedodd** [comment]
Going to close this for now. Docs and guide are pretty solid on this now.
