### ISSUE TITLE
Bug with get_log_entries function

### ISSUE THREAD

**Issue by MarinPostma** [async-raft/async-raft#73]
The current prototype for the `get_log_entries` is `get_log_entries(&self, start: u64, stop: u64)` where start and stop are the bounds of an excluded upper bound interval. In the `MemStore` implementation,  you can notice that it is translated into a [range](https://doc.rust-lang.org/std/ops/struct.Range.html): [here](https://github.com/async-raft/async-raft/blob/master/memstore/src/lib.rs#L193). Turns out that when start = stop, `MemStore` returns an empty vec with this implementation. This becomes problematic because the replication module, [here](https://github.com/async-raft/async-raft/blob/master/async-raft/src/replication/mod.rs#L259) calls it with start = stop, which returns nothing, and triggers a snapshot.

I have encountered this bug when implementing raft for myself, with the same reasoning as the one in `MemStore`. Now, the fix is straightforward in MemStore, but I'd like to suggest that we change the prototype of `get_log_entries` to `get_log_entries<R: RangeBounds<u64>>(&self, range: T)`. This would, in my sense, dismiss any ambiguities.

I have branch with both solution implemented locally, I can make a PR with whichever solution is preferred.

**Comment by thedodd** [comment]
@MarinPostma it does appear as though you are correct. The memstore appears to be implemented correctly according to the requirements of the `get_log_entries` trait method. However, [the call here](https://github.com/async-raft/async-raft/blob/master/async-raft/src/replication/mod.rs#L259) `self.storage.get_log_entries(conflict.index, conflict.index)` should be updated to be `self.storage.get_log_entries(conflict.index, conflict.index+1)` (the +1 at the end). Doing so will ensure that the conflict index is actually selected.

@MarinPostma do you want to open a bug fix PR for this? Should just be that one mini change. I'll review the code base to ensure we don't have any other subtle "off by 1" bugs.

**Comment by MarinPostma** [comment]
Thanks for the clarification @thedodd, opening a pr ASAP
