### ISSUE TITLE
Leader blocked when apply_entry_to_state_machine takes to long

### ISSUE THREAD

**Issue by MarinPostma** [async-raft/async-raft#76]
In my use case, applying a log entry may take a while, and I found that this would make the leader unable to make progresses, causing it to timeout, and trigger new elections. Here what I have found so far:

- in `LeaderState::run` the `select!` blocks on `handle_replica_event` (after the log entry has been commited)
- `handle_replica_event` calls `handle_update_match_index` that repeatedly call `client_request_post_commit` for each entry to be applied. 

During all this time, the loop in `run` is blocked performing this task, and can't perform it's other tasks, such as sending heartbeats. This causes elections timeout, and for some reason that I haven't yet completely understand (probably in my implementation) the entry **is not applied on the leader node, but is on the other nodes**.

The log application process should not block the leader from operating normally. A possible fix would be to offload the work performed by `client_request_post_commit` to another thread, and instead of call it directly, `handle_update_match_index` enqueues entries to be applied. I am currently experimenting with this solution.

**Comment by MarinPostma** [comment]
Hey,

Yes I mean applying to the state machine. Indeed, I am aware of that trade-off, but writes throughput is not a problem for me.

**Comment by MarinPostma** [comment]
Thanks for all these advices!

As you suggested, I had initially though of doing the heavy lifting **after** the raft component, but it turned out to be an issue. Currently, I replicate write operations **prior** to indexation. Document indexing is the task that requires a lot of time. 
Before, those task would just be enqueued, and as far as raft was concerned, this was instantaneous, and there would be no problem. However, when the need for snapshot arised, I had to make sure that all the enqueued indexing operation where processed before I could create a snapshot. This adds the need for synchronization between the indexing and the snapshot creation tasks. With this in mind it, the update queue now appears redundant, and synchronization mechanisms have to be found so I can reliably create snapshots, hence having raft synchronously proceeding to the indexation. I will try synchronizing during snapshoting, but this is not very satisfying.
---

I have re-read the paper  this is what I understand:
As you pointed out, `broadcastTime` is the average time it takes for a server to send a RPC and receives a response, this we both agree on, but looking at the implementation guideline on page 4 of the paper, it says (for `AppendEntries` RPC):
> Receiver implementation:
> 1. Reply false if term < currentTerm (§5.1)
> 2. Reply false if log doesn’t contain an entry at prevLogIndex
> whose term matches prevLogTerm (§5.3)
> 3. If an existing entry conflicts with a new one (same index
> but different terms), delete the existing entry and all that
> follow it (§5.3)
> 4. Append any new entries not already in the log
> 5. If leaderCommit > commitIndex, set commitIndex =
> min(leaderCommit, index of last new entry)

To me, the `AppendEntries` RPC is not in charge of *actually* replicating the state to the state machine. According to this, `broadcastTime` is not correlated to the time it takes to perform the entry's operation, is that right?

**Comment by thedodd** [comment]
@MarinPostma thanks for the background. That definitely helps. I do want to ask more about the indexing operation ... however, I think that you should be free to tackle this problem in whatever way you see fit as long as it is within the bounds of Raft safety ... and this should be.

So, that said, I was thinking about this a bit earlier, and I remembered that we do indeed make calls to `replicate_to_state_machine_if_needed` from within the `handle_append_entries_request` handler and we await the response. So, in this particular case, that is what is causing the delay on responding to heartbeats in a timely fashion.

I think a good solution for this is to simply have followers spawn a task which monitors this state asynchronously and applies to the state machine on its own as need data becomes available and it is able to prove that it is safe to apply to the state machine safely according to the Raft protocol.

I opened #12 A LONG time ago, and it might be good to update that issue with an additional requirement to move the `replicate_to_state_machine_if_needed` calls off of the hot path of the append entries handler. I'll do that now and then prioritize those changes. Doing so should address the issue you are facing.

**Comment by MarinPostma** [comment]
Many thanks @thedodd, let me know if you want help with the implementation.

**Comment by thedodd** [comment]
@MarinPostma just wanted to let you know that I've started hacking on this now. I'm blocked until its done, so it should be done quite soon `:)`.
