### ISSUE TITLE
When there is only one node in the cluster, calling `Raft::client_read` fails.

### ISSUE THREAD

**Issue by sunli829** [async-raft/async-raft#82]
I'm so sorry, I'm here again. 😂

When there is only one node in the cluster, calling `Raft::client_read` fails.
The error message returned is `too many requests failed, could not confirm leadership`.

Did I do something wrong?

Thank you again for your contribution to this awesome library!

**Comment by thedodd** [comment]
Haha @sunli829 no, don't apologize! I'm genuinely happy that you're using the library and taking the time to report issues like this! Thank you!

This is definitely a bug. Fortunately a simple one. When I first wrote the handler responsible for this code path, I evidently did not account for the single-node cluster topology. Should have a fix quite soon.

**Comment by thedodd** [comment]
All done. I updated the `singlenode.rs` integration test as well. It was already asserting write-path functionality, so I just needed to add a line to test read-path functionality as well. We should be g2g!

Thanks again for taking the time to open the issue.

**Comment by sunli829** [comment]
YOU ARE THE BEST! THANK YOU! 😀
