### ISSUE TITLE
Crate imports Tokio 0.1

### ISSUE THREAD

**Issue by semtexzv** [async-raft/async-raft#86]
`async-raft` depends on `tracing-futures 0.2.4`, but this dependency somehow pulls in `tokio 0.1`.

**Comment by thedodd** [comment]
@semtexzv thanks for reporting this. I'll look into the dependency graph and try to see where this is coming from. Hopefully it is just a matter of enabling or disabling a feature switch on one of our deps.

**Comment by thedodd** [comment]
@semtexzv I've tracked down the issue. I'll have the fix merged into master shortly, and the fix will go out as part of `0.6.0-alpha.2`.
