### ISSUE TITLE
How is `Snapshot: AsyncWrite` utilized?

### ISSUE THREAD

**Issue by nkconnor** [async-raft/async-raft#93]
There must be something obvious I'm missing but  wondering if you could point me to where/why snapshot has this bound? Is the library making some assumptions somewhere and is writing to the snapshot outside of the `RaftStorage` interface (which does not use this bound as far as I can tell from the trait implementation)?

**Comment by thedodd** [comment]
Hey there. That something obvious is located here: https://github.com/async-raft/async-raft/blob/master/async-raft/src/core/install_snapshot.rs

To break things down a bit:
- the `do_log_compaction` is internal to a node. It is triggered periodically based on snapshot settings.
- the process of a leader streaming a snapshot to a follower is a different story. That is part of the code I've linked to above. In these cases, the follower will generate a blank snapshot, and then Raft utilizes the `AsyncWrite` trait to actually write the bytes which are streamed in from the leader to the snapshot file.

Cheers `:)`

**Comment by thedodd** [comment]
Let me know if there is anything I can help with! Do you think some documentation improvements are merited on this front? I have a PR currently open addressing some other ergonomics issues. Happy to incorporate doc improvements as well.

**Comment by thedodd** [comment]
@nkconnor does that answer your question?

**Comment by nkconnor** [comment]
Yes this definitely makes sense now! Appreciate the very prompt response. I do think adding this as context would be helpful in the documentation.
