### ISSUE TITLE
`client_read` and `client_write` should share a Mutex lock

### ISSUE THREAD

**Issue by xu-cheng** [async-raft/async-raft#98]
When using `client_read` and `client_write`  without Mutex lock, unexpected issues would appear. It takes me a very long time to realize the issue. May I suggest to include a Mutex lock inside these two functions? Alternatively, the document should emphasize the application need to ensure there is no concurrent  `client_read` and `client_write`.

**Comment by thedodd** [comment]
> unexpected issues would appear

What unexpected issues? All requests into the Raft instance are pipelined through a shared input channel. All work is executed in the order which it is received. What is the issue you are concerned about? Stale reads?

**Comment by xu-cheng** [comment]
I am not entirely sure the root cause. But I encounter errors from either `RaftStorage::get_log_entries` or  `RaftStorage:: do_log_compaction` (from `log.get(&last_applied_log)` ).  Carefully examining the log, I usually found the following events:

1. `handle_append_entries_request` successfully applied the write the request from the `client_write`.
2. `handle_append_entries_request` received another `AppendEntriesRequest` with the same `prev_log_index` and `prev_term_index` as the above `AppendEntriesRequest` but with empty `entries`. It seems that it comes from `client_read` request.
3. Consistency check in the above `handle_append_entries_request` called `delete_logs_from` to delete the last applied log from the `client_write`.
4. `get_log_entries` or `do_log_compaction` failed because the requested log was deleted.

By applying Mutex for `client_read` and `client_write`, the above issues become very rarely. Maybe this is a bug in the library? Any advice?

FYI, the workflow in my application works like this:
* A client randomly picks a node to find the current leader. The picked node will call `client_read` to determine the leader.
* Then, the client sends the write request to the leader.

**Comment by xu-cheng** [comment]
Ok, I have found ways to demonstrate my problem. I created the following test case:


```rust
mod fixtures;

use std::sync::Arc;
use std::time::Duration;

use anyhow::Result;
use async_raft::config::SnapshotPolicy;
use async_raft::Config;
use async_raft::error::ClientReadError;
use tokio::time::delay_for;

use fixtures::RaftRouter;

fn pause() {
    use std::io::{stdin, Read};
    println!("Press Enter to continue...");
    stdin().read(&mut [0]).unwrap();
}

/// RUST_LOG=async_raft,memstore,client_writes=trace,info cargo test -p async-raft --test concurrent | tee log.txt
#[tokio::test(core_threads = 4)]
async fn concurrent() -> Result<()> {
    fixtures::init_tracing();

    let config = Arc::new(
        Config::build("test".into())
        .snapshot_policy(SnapshotPolicy::LogsSinceLast(2))
        .validate()
        .expect("failed to build Raft config"),
    );
    let router = Arc::new(RaftRouter::new(config.clone()));

    const NODES: u64 = 8;

    for i in 0..NODES {
        router.new_raft_node(i).await;
    }

    tracing::info!("--- initializing cluster");
    router.initialize_from_single_node(0).await?;
    delay_for(Duration::from_secs(2)).await;

    let leader = router.leader().await.expect("leader not found");

    let r = router.clone();
    tokio::spawn(async move {
        for i in 0.. {
            let w_info = format!("{}", i);
            r.client_request(leader, &w_info, i).await;
            delay_for(Duration::from_millis(10)).await;
        }
    });

    for i in 0..NODES {
        let r = router.clone();
        tokio::spawn(async move {
            loop {
                match r.client_read(i).await {
                    Ok(_) | Err(ClientReadError::ForwardToLeader(_)) => {}
                    Err(ClientReadError::RaftError(e)) => {
                        tracing::error!({error=%e}, "error from read request");
                        panic!(e);
                    }
                }
                delay_for(Duration::from_millis(10)).await;
            }
        });
    }

    pause();
    Ok(())
}
```

If you run the program for some times, you may find the error messages in the log:
```
Jan 04 23:09:51.310 ERROR main{id=2 cluster=test}:run{id=2 raft_state="follower"}:handle_replicate_to_sm_result:trigger_log_compaction_if_needed:beginning new log compaction process: async_raft::core: error while generating snapshot error=a query was received which was expecting data to be in place which does not exist in the log
```

This is caused by the failed log read in `do_log_compaction`.

I also found the existing `MemStore::get_log_entries` would mask the problem. If you apply the following changes, it will show the `get_log_entries` actually failed.

```diff
diff --git a/memstore/src/lib.rs b/memstore/src/lib.rs
index 852c7b2..05525fa 100644
--- a/memstore/src/lib.rs
+++ b/memstore/src/lib.rs
@@ -199,7 +199,8 @@ impl RaftStorage<ClientRequest, ClientResponse> for MemStore {
             return Ok(vec![]);
         }
         let log = self.log.read().await;
-        Ok(log.range(start..stop).map(|(_, val)| val.clone()).collect())
+        let res = (start..stop).map(|i| log.get(&i).ok_or_else(|| anyhow::anyhow!("log not found"))).collect::<Result<Vec<_>>>()?;
+        Ok(res.into_iter().cloned().collect())
     }
 
     #[tracing::instrument(level = "trace", skip(self))]
```

With this, you will observe the following messages in the log:
```
Jan 04 23:09:51.307 ERROR main{id=6 cluster=test}:run{id=6 raft_state="follower"}:handle_append_entries_request{term=1 leader_id=0 prev_log_index=1 prev_log_term=1 leader_commit=2}:map_fatal_storage_error{err=log not found}: async_raft::core: fatal storage error, shutting down error=log not found id=6
```

This results that this node got shutdown and all subsequent requests failed.
```
Jan 04 23:09:51.319 ERROR main{id=0 target=6 cluster=test}:run{state="line-rate"}:send_append_entries: async_raft::replication: error sending AppendEntries RPC to target error=Raft is shutting down
```

**Comment by thedodd** [comment]
@xu-cheng something that I'm concerned about here is that much of this depends on the implementation of the storage engine you are using, specifically I mean the way that you implemented the `RaftStorage` trait. If some of the methods are not implemented correctly, then we could end up seeing behavior like this. 

That said, are you observing this behavior purely from the `memstore` RaftStorage impl?

**Comment by thedodd** [comment]
However, I will say, based on your above statement:

> 1. `handle_append_entries_request` successfully applied the write the request from the `client_write`.
> 2. `handle_append_entries_request` received another `AppendEntriesRequest` with the same `prev_log_index` and `prev_term_index` as the above `AppendEntriesRequest` but with empty `entries`. It seems that it comes from `client_read` request.

I can see how the append_entries RPC handler might misbehave. Let me review the code there to see if there is an obvious problem.

**Comment by thedodd** [comment]
Ok, definitely a bug in the code. It is a bug due to not accounting for this case which you've mentioned. Basically, what we can do to cleanly and easily mitigate this issue is:
- just after the code block here https://github.com/async-raft/async-raft/blob/master/async-raft/src/core/append_entries.rs#L43-L47
- we can introduce a block which will check if the payload is empty (a heartbeat payload), and if so then we can just immediately return from the handler with an Ok.
- because the payload will be empty, there is no concern about ordering as nothing will be appended to the log.
- also, before this location in the code, we will be performing the term comparisons and such, so we will only progress to this point if it is a heartbeat from the leader of the current term.

As such, all of the base-line safety invariants will be upheld. And actually, check this out: https://github.com/async-raft/async-raft/blob/master/async-raft/src/core/append_entries.rs#L53-L65 Looks like at some point I moved that block of code into log alignment check. For heartbeats, that should be unnecessary, so we can actually just move that block up and out of the alignment check as I mention above.

@xu-cheng thoughts?

**Comment by xu-cheng** [comment]
Sorry, I don't understand the internal code well enough to comment on how to fix bug. However, may I suggest:
* Update `MemStore::get_log_entries` like mentioned above so it can stop unmasking the bug. That is it should retrieve every entries in the `start..stop`. The currently implementation will simple ignore the problem if the requested entry does not exist.
* Maybe create a test case to reliably reproduce the problem so it can be run inside CI?
